@startuml

skinparam Shadowing 1.0
' avoid problems with angled crows feet
skinparam linetype ortho

title
Périmètre final de l'usage
end title

entity CORE.PATIENT {
  * {field} PATIENT_NI NUMBER (38, 0) NOT NULL
  * {field} NAME VARCHAR2 (50) NULL
  * {field} FIRST_NAME VARCHAR2 (50) NULL
  * {field} GENDER CHAR (1) NULL
  * {field} BIRTH_DATE DATE NULL
}

entity CORE.SEJOUR {
  * {field} SEJOUR_NI NUMBER (38, 0) NOT NULL
  * {field} PATIENT_NI NUMBER (38, 0) NOT NULL
  * {field} SEJOUR_TYPE VARCHAR2 (50) NOT NULL
  * {field} SEJOUR_START DATE NULL
  * {field} SEJOUR_END DATE NULL
}

entity CORE.BIOLOGY {
  * {field} BIOLOGY_NI NUMBER (38, 0) NOT NULL
  * {field} BIOLOGY_DATE DATE NULL
  * {field} BIOLOGY_CODE VARCHAR2 (50) NULL
  * {field} BIOLOGY_VALUE NUMBER (4, 2) NULL
  * {field} BIOLOGY_UNIT VARCHAR2 (10) NULL
}



CORE.SEJOUR }o..o| CORE.PATIENT


@enduml
