@startuml

' quoique la syntaxe uml des diagrammes de cas d'utilisation soit utiliser, cette figure n'est qu'illustrative. 

skinparam actorStyle awesome

actor :Professionnel de santé: as pds

package Orbis{
  usecase "Cas 2 : Saisie via un autre formulaire" as form
  usecase "Cas 1 : Saisie via le formulaire\n'Courbe de Croissance'" as cdc
  usecase "Enrichissement de la table <i>Messungen</i>" as mess
}

usecase "Alimentation de l'Entrepôt de Données de Santé" as eds

pds --> form
pds --> cdc
form --> mess
cdc --> mess
mess --> eds

@enduml