@startuml

' quoique la syntaxe uml des diagrammes de cas d'utilisation soit utilisée, cette figure n'est qu'illustrative. 

skinparam actorStyle awesome

actor :Professionnel de santé: as pds

package DPI{
  usecase "Cas 2 : Saisie via un autre formulaire" as form
  usecase "Cas 1 : Saisie via le formulaire\n'Courbe de Croissance'" as cdc
  usecase "Table de centralisation des mesures standardisées" as mess
}

usecase "Alimentation du Hub de données" as eds

pds --> form
pds --> cdc
form --> mess
cdc --> mess
mess --> eds

@enduml