-- CORE.ACTE definition

-- Drop table

-- DROP TABLE CORE.ACTE;

CREATE TABLE CORE.ACTE (
     ACTE_NI NUMBER(38,0) NOT NULL,
     PATIENT_NI NUMBER(38,0) NOT NULL,
     SEJOUR_NI NUMBER(38,0) NOT NULL,
     CODE VARCHAR2(13) NOT NULL,
     DATE_START DATETIME,
     DATE_END DATETIME,
     CONSTRAINT PK_DIAG PRIMARY KEY (ACTE_NI),
     CONSTRAINT SYS_C00109710 CHECK ("ACTE_NI" IS NOT NULL),
     CONSTRAINT FK1_PATIENT FOREIGN KEY (PATIENT_NI) REFERENCES CORE.PATIENT(PATIENT_NI),
     CONSTRAINT FK2_SEJOUR FOREIGN KEY (SEJOUR_NI) REFERENCES CORE.SEJOUR(SEJOUR_NI)
);
CREATE UNIQUE INDEX PK_ACTE ON CORE.ACTE (ACTE_NI);