-- CORE.PATIENT definition

-- Drop table

-- DROP TABLE CORE.PATIENT;

CREATE TABLE CORE.PATIENT (
    PATIENT_NI NUMBER(38,0) NOT NULL,
    VIP CHAR(1) NOT NULL,
    NAME VARCHAR2(50) NULL,
    FIRST_NAME VARCHAR2(50) NULL,
    GENDER CHAR(1),
    BIRTH_DATE DATE NULL,
    NIR VARCHAR2(13) NULL,
    CONSTRAINT PK_PATIENT PRIMARY KEY (PATIENT_NI),
    CONSTRAINT SYS_C00109590 CHECK ("PATIENT_NI" IS NOT NULL),
    CONSTRAINT SYS_C00109591 CHECK ("VIP" IS NOT NULL)
);
CREATE UNIQUE INDEX PK_PATIENT ON CORE.PATIENT (PATIENT_NI);